services:
  mysql-db:
    image: mysql:8.0
    container_name: real_estate_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: real_estate_backend
    restart: unless-stopped
    depends_on:
      - mysql-db
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: real_estate_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8081:80"   # Port Nginx 80 dans le conteneur

volumes:
  mysql_data: